version: '3.8'

x-environment: &common-env
  DB_DRIVER: ${DB_DRIVER}
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}
  DB_USERNAME: ${DB_USERNAME}
  DB: ${DB}
  DB_PASSWORD: ${DB_PASSWORD}
  JWT_SECRET: ${JWT_SECRET}

services:
  app:
    container_name: app
    environment:
      <<: *common-env

    build: .
    ports:
      - "1373:1373"
    restart: always
    depends_on:
      - postgres
    networks:
      - dockernet

  postgres:
    image: postgres:12-alpine
    restart: always
    volumes:
      - general_postgres_data:/var/lib/postgresql/data/
    container_name: postgres
    ports:
      - "54392:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - dockernet

volumes:
  general_postgres_data:

networks:
  dockernet:
    external: true
